version: '3'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Mypassword01
      - MYSQL_DATABASE=OctoKon

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
