name: Zip Repository

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

 Login: 
   runs-on: ubuntu-latest

   steps:

    - name: Login to Octopus Deploy
      uses: OctopusDeploy/login@v1.0.1
      with:
       server: "https://adamclose.octopus.app/"
       service_account_id: "81"
