name: Zip Repository

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

 Octopus: 
   runs-on: ubuntu-latest

   steps:

    - name: create-version-number
      run: echo "version=$(date +'%Y.%m.%d')" >> "$GITHUB_OUTPUT"

    - name: Login to Octopus Deploy
      uses: OctopusDeploy/login@v1.0.1
      with:
       server: "https://adamclose.octopus.app/"
       service_account_id: "7bca9f0c-70a6-4e95-a9ff-6aae2d170d43"

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create ZIP file
      run: zip -r octopus.demo.templae.zip .

    - name: Push to Octopus
      uses: OctopusDeploy/push-package-action@v3.0.4
      with: 
        packages: octopus.demo.templae.zip
       
