name: Zip Repository

on:
  workflow_dispatch:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create ZIP file
      run: zip -r repo.zip .

    - name: Upload ZIP file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: repository-zip
        path: repo.zip